spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ecommerce
    username: user
    password: pass
    initialization-mode: always

  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    org.springframework.data.mongodb.core: DEBUG
    org.springframework.web.reactive: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
    reactor.netty: WARN
